# Generated by Django 5.0.6 on 2024-05-20 18:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('ANIMATION', 'Animation'), ('COMEDY', 'Comedy'), ('CRIME', 'Crime'), ('DRAMA', 'Drama'), ('DOCUMENTARY', 'Documentary'), ('SCI-FI', 'Sci-Fi'), ('FAMILY', 'Family'), ('HISTORY', 'History'), ('FANTASY', 'Fantasy'), ('HORROR', 'Horror'), ('MUSICAL', 'Musical'), ('MYSTERY', 'Mystery'), ('ROMANCE', 'Romance'), ('THRILLER', 'Thriller'), ('WAR', 'War'), ('WESTERN', 'Western')], max_length=50)),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
