# Generated by Django 5.0.6 on 2024-06-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0004_article_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
